### ISSUE TITLE
Introduce .rustfmt.toml

### ISSUE THREAD

**Issue by PoOnesNerfect** [BenJeau/cargo-interactive-update#15]
**Is your feature request related to a problem? Please describe.**
Introduce `.rustmft.toml` file to standardize formatting within the project

**Describe the solution you'd like**
Here are the rules that I use for my projects over the years, for example.

```toml
unstable_features = true

max_width = 80
single_line_let_else_max_width = 60
single_line_if_else_max_width = 60

tab_spaces = 4
array_width = 60
struct_lit_width = 20
struct_variant_width = 20
indent_style = "Block"

condense_wildcard_suffixes = true
imports_granularity = "Crate"
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
overflow_delimited_expr = true
reorder_impl_items = true
wrap_comments = true
```
